import type { NextPage } from "next";
import Head from "next/head";
import PostCard, { PostCardProps } from "../components/post/PostCard/PostCard";
import PostEditor from "../components/post/PostEditor/PostEditor";
// import PostsGrid from '../components/ui/Grid/PostsGrid/PostsGrid'
import PostsSlider from "../components/post/PostsSlider/PostsSlider";
import ProductCard from "../components/product/ProductCard/ProductCard";

const posts: PostCardProps[] = [
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
  {
    title:
      "Architectural Engineering Wonders of the modern era for your Inspiration",
    category: "personal growth",
    date: "2020-01-01",
    author: "Saad ur Rehman",
    image: "/avatar.png",
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/quill-editor.css" />
      </Head>

      <div className="p-3 mx-auto">
        <ProductCard
          title="My Life"
          thumbnail="/avatar.png"
          href="/"
          price={100}
        />
      </div>
    </div>
  );
};

export default Home;
